training_args:
  output_dir: "./results"
  evaluation_strategy: "epoch"
  learning_rate: 2e-5
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  num_train_epochs: 3
  weight_decay: 0.01
  logging_dir: "./logs"
  logging_steps: 10
  save_steps: 100
  report_to: "none"

model_args:
  num_of_classes: {{ target_variables[target_variable].num_of_classes }}
  hubert_model_name: "facebook/hubert-base-ls960"

folders:
  json_folder: /./
  audio_folder: /./
  output_base: ./results
  experiment_name: "{{ target_variable }}_classification"
